# Generated by Django 3.1.6 on 2021-02-13 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='user_default.png', upload_to='avatar/')),
                ('cover', models.ImageField(blank=True, default='cover_default.png', upload_to='cover/')),
                ('bio', models.TextField(blank=True, max_length=300)),
                ('phone', models.IntegerField(blank=True, default=False)),
                ('web', models.CharField(blank=True, max_length=100)),
                ('gander', models.CharField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='غير محدد', max_length=40)),
                ('country', models.CharField(blank=True, choices=[('المغرب', 'المغرب'), ('الجزئر', 'الجزئر'), ('تونس', 'تونس'), ('ليبيا', 'ليبيا'), ('فلسطين', 'فلسطين'), ('مصر', 'مصر'), ('مورتنيا', 'مورتنيا'), ('السودان', 'السودان'), ('الكويت', 'الكويت'), ('العراق', 'العراق'), ('الإمرات', 'الإمرات')], default='غير محدد', max_length=40)),
                ('is_admin', models.BooleanField(blank=True, default=False)),
                ('is_publesher', models.BooleanField(blank=True, default=False)),
                ('is_blocked', models.BooleanField(blank=True, default=False)),
                ('birth', models.CharField(blank=True, max_length=300)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('block', models.ManyToManyField(blank=True, related_name='user_block', to=settings.AUTH_USER_MODEL)),
                ('follow', models.ManyToManyField(blank=True, related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friend', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('viewrs', models.ManyToManyField(blank=True, related_name='user_viewrs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('send', 'send'), ('accepted', 'accepted')], max_length=10)),
                ('update', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='users.profile')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Public',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.BooleanField(blank=True, default=True)),
                ('phone', models.BooleanField(blank=True, default=True)),
                ('web', models.BooleanField(blank=True, default=True)),
                ('bio', models.BooleanField(blank=True, default=True)),
                ('gander', models.BooleanField(blank=True, default=True)),
                ('friends', models.BooleanField(blank=True, default=True)),
                ('country', models.BooleanField(blank=True, default=True)),
                ('birth', models.BooleanField(blank=True, default=True)),
                ('created', models.BooleanField(blank=True, default=True)),
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
