# Generated by Django 3.2.7 on 2021-11-20 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_profile_earning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gander',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
