# Generated by Django 4.1.5 on 2023-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20220209_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='trafiq',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
