# Generated by Django 4.1.9 on 2023-07-15 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_profile_trafiq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='user',
        ),
        migrations.RemoveField(
            model_name='public',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pusblisher',
            name='user',
        ),
        migrations.DeleteModel(
            name='PusblisherCategoryArabic',
        ),
        migrations.DeleteModel(
            name='PusblisherCategoryEnglish',
        ),
        migrations.DeleteModel(
            name='PusblisherCategoryfranch',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Media',
        ),
        migrations.DeleteModel(
            name='Public',
        ),
        migrations.DeleteModel(
            name='Pusblisher',
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
