# Generated by Django 4.0.5 on 2022-09-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0002_alter_post_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freewsad.language'),
        ),
    ]
