# Generated by Django 4.0.5 on 2022-09-21 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0003_postlist_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='postlist',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
