# Generated by Django 4.0.5 on 2022-11-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0004_postlist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imageURL',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
