# Generated by Django 4.0.5 on 2022-11-16 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0005_post_imageurl_alter_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='AdminImage/'),
        ),
    ]
