# Generated by Django 4.1.5 on 2023-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0011_alter_file_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_type',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Book Type '),
        ),
    ]
