# Generated by Django 4.1.5 on 2023-02-04 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0012_book_size_alter_book_book_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
