# Generated by Django 4.1.5 on 2023-02-12 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0013_remove_book_views_book_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='link',
        ),
        migrations.AlterField(
            model_name='book',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Body'),
        ),
    ]
