# Generated by Django 4.1.5 on 2023-02-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0014_remove_book_link_alter_book_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
