# Generated by Django 4.1.9 on 2023-05-26 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0016_alter_postcomment_options_remove_postcomment_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcomment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_comment', to='freewsad.post'),
        ),
    ]
