# Generated by Django 4.1.9 on 2023-05-26 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freewsad', '0017_alter_postcomment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postcomment',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='postcomment',
            old_name='date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='postcomment',
            name='full_name',
        ),
        migrations.AddField(
            model_name='postcomment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='like_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='postcomment',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='body',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='postcomment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
