# Generated by Django 4.1.9 on 2023-06-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0018_alter_postcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postcategory',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, null=True, unique=True),
        ),
    ]
