# Generated by Django 4.1.9 on 2023-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0020_remove_template_add_to_cart_remove_template_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
