# Generated by Django 4.1.9 on 2023-07-17 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freewsad', '0022_location_video_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videocomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
