# Generated by Django 4.1.9 on 2023-07-17 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0024_alter_videocomment_movie_alter_videocomment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='videocomment',
            old_name='movie',
            new_name='video',
        ),
    ]
