# Generated by Django 4.1.9 on 2023-08-12 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0025_rename_movie_videocomment_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='duration',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='quality',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
