# Generated by Django 4.1.9 on 2023-08-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0026_quality_duration_quality_height_quality_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='quality',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Quality'),
        ),
    ]
