# Generated by Django 4.1.9 on 2023-08-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0027_alter_quality_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_qualities', to='freewsad.video'),
        ),
    ]
