# Generated by Django 4.1.9 on 2023-08-12 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freewsad', '0028_alter_quality_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'ordering': ['height']},
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='video_category', to='freewsad.postcategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=freewsad.models.filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='freewsad.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='video',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freewsad.postlist', verbose_name='Play list'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
