# Generated by Django 4.1.9 on 2023-08-13 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freewsad', '0030_alter_book_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='VidoeList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(auto_created=True, blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=300, verbose_name='Name ')),
                ('description', models.TextField(blank=True, null=True)),
                ('tags', models.CharField(blank=True, max_length=200, null=True, verbose_name='Tags ')),
                ('image', models.ImageField(default='default-post.png', upload_to=freewsad.models.filename)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ManyToManyField(blank=True, related_name='video_list_category', to='freewsad.postcategory', verbose_name='Category')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freewsad.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_lists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freewsad.vidoelist', verbose_name='Play list'),
        ),
    ]
