# Generated by Django 4.1.9 on 2023-08-13 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0032_alter_video_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='freewsad.vidoelist', verbose_name='Play list'),
        ),
    ]
