# Generated by Django 4.1.9 on 2023-08-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0033_alter_video_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='quality',
            name='url',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
