# Generated by Django 4.1.9 on 2023-08-13 17:12

from django.db import migrations, models
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0034_quality_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quality',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=freewsad.models.filename, verbose_name='Video'),
        ),
    ]
