# Generated by Django 4.1.9 on 2023-08-14 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('freewsad', '0035_alter_quality_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VidoeList',
            new_name='VideoList',
        ),
        migrations.RenameField(
            model_name='videoview',
            old_name='vidoe',
            new_name='video',
        ),
        migrations.RemoveField(
            model_name='book',
            name='views',
        ),
        migrations.CreateModel(
            name='BookView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freewsad.book')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freewsad.location')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.ManyToManyField(through='freewsad.BookView', to='freewsad.location'),
        ),
    ]
