# Generated by Django 4.1.9 on 2023-08-31 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0038_alter_book_category_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='freewsad.language', verbose_name='Language'),
        ),
    ]
