# Generated by Django 4.1.9 on 2023-11-29 17:08

from django.db import migrations, models
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0040_alter_location_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=freewsad.models.filename, verbose_name='Image'),
        ),
    ]
