# Generated by Django 4.1.9 on 2023-11-29 17:10

from django.db import migrations, models
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0041_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=freewsad.models.filename, verbose_name='File'),
        ),
    ]
