# Generated by Django 4.1.9 on 2024-04-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0042_alter_book_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='removed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
