# Generated by Django 4.1.9 on 2024-08-11 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0043_book_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='istm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
