# Generated by Django 4.1.9 on 2024-08-11 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0045_rename_istm_book_istn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='istn',
            new_name='isbn',
        ),
    ]
