# Generated by Django 4.1.9 on 2024-08-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0046_rename_istn_book_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='readed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
