# Generated by Django 4.1.9 on 2023-11-25 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Linke',
            new_name='Link',
        ),
    ]
