# Generated by Django 4.1.9 on 2023-11-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_rename_linke_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='urls',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='link',
            field=models.URLField(max_length=1000),
        ),
    ]
