# Generated by Django 4.1.9 on 2023-11-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_rename_urls_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='url',
        ),
        migrations.AddField(
            model_name='link',
            name='custom',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
