# Generated by Django 4.1.9 on 2023-11-27 19:46

from django.db import migrations, models
import django.db.models.deletion
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0040_alter_location_created_at'),
        ('tools', '0005_remove_link_url_link_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=freewsad.models.filename)),
                ('identity', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('gender', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacebookGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=freewsad.models.filename)),
                ('url', models.URLField(max_length=1000)),
                ('members', models.IntegerField()),
                ('status', models.BooleanField()),
                ('description', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freewsad.language')),
            ],
        ),
    ]
