# Generated by Django 4.1.9 on 2024-01-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_account_facebookgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgroup',
            name='description',
            field=models.TextField(),
        ),
    ]
