# Generated by Django 4.1.9 on 2024-01-04 16:46

from django.db import migrations, models
import django.db.models.deletion
import freewsad.models


class Migration(migrations.Migration):

    dependencies = [
        ('freewsad', '0042_alter_book_file'),
        ('tools', '0008_alter_account_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgroup',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='image',
            field=models.ImageField(upload_to=freewsad.models.filename, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='freewsad.language', verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='members',
            field=models.IntegerField(verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Group name'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='status',
            field=models.BooleanField(verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='facebookgroup',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='Link'),
        ),
    ]
